server:
    port: 9090
#    context-path: /

#logging:
#    level:
#        tk.mybatis: DEBUG


#    mvc:
#        view:
#            prefix: /templates/
#            suffix: .ftl
#    data:
#        mongodb:
#            host: 127.0.0.1
#            port: 27017
#            username: root
#            password: rootroot
#            database: order

mybatis:
    type-aliases-package: tk.mybatis.springboot.model
    mapper-locations: classpath:mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true



#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        druid:
            url: jdbc:mysql://127.0.0.1:3306/sss?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
            username: root
            password: root
            initial-size: 20
            max-active: 300
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: select 1 from dual
            test-while-idle: true
            test-on-borrow: true
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                login-username: druid
                login-password: dingmin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: false
                wall:
                    config:
                        multi-statement-allow: true
    servlet:
        multipart:
            max-file-size: 30MB
            max-request-size: 50MB



sys:
   img:
#     uploadPath: D:/img/
#     readPath: /img/
     uploadPath: /home/img/
     readPath: http://121.36.9.237/
#    params: count=countSql

logging:
  path: /data/java/logs
  file:
    max-size: 300MB
