server:
    port: 9090
#    context-path: /

logging:
    level:
        tk.mybatis: TRACE

spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/sss?serverTimezone=UTC
        username: root
        password: root
        # 使用druid数据源 
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
#    mvc:
#        view:
#            prefix: /templates/
#            suffix: .ftl
#    data:
#        mongodb:
#            host: 127.0.0.1
#            port: 27017
#            username: root
#            password: rootroot
#            database: order

mybatis:
    type-aliases-package: tk.mybatis.springboot.model
    mapper-locations: classpath:mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true



#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql